# PROGRAM:     TransactionDAO (DAO - Data Access Object)
# PURPOSE:     Data access layer of GillPay application that handles the read
#                   and write operations to application CSV
# INPUT:       Transaction data passed in by clients
# PROCESS:     DAO uses both CSV and Pandas to perform read and write operations
#                   to the
# OUTPUT:      Outputs generated by the program.
# HONOR CODE:  On my honor, as an Aggie, I have neither given nor
#               received unauthorized aid on this academic work.

import csv
import pandas
from collections.abc import Iterable
from pandas.core.interchange.dataframe_protocol import DataFrame
from src.transaction import Transaction


class TransactionDAO:

    def __init__(self, datasource="../data/gillpay_data.csv"):
        self.datasource = datasource

    def GetDataFrame(self) -> DataFrame:
        return pandas.read_csv(self.datasource)

    def GetTransactions(self) -> Iterable[Transaction]:
        try:
            dataFrame = self.GetDataFrame()
            return dataFrame.values.tolist()
        except FileNotFoundError:
            print(f"Unable to find file {self.datasource}")

    def GetTransactionByType(self):
        return None

    def SaveTransaction(self, transaction: Transaction):

        try:
            with open(self.datasource, "a", newline="") as csv_file:
                csvWriter = csv.writer(csv_file)
                newRow = [transaction.transaction_type, transaction.category,
                          transaction.amount, transaction.date]
                csvWriter.writerow(newRow)
        except FileNotFoundError:
            print(f"Unable to find file {self.datasource}")
